---
- name: Spawn ShadowSocks
  community.docker.docker_container:
    name: shadowsocks
    image: ghcr.io/shadowsocks/ssserver-rust:latest
    ports:
      - 'your port here /tcp'
    restart_policy: unless-stopped
    volumes:
      - "{{ container_path }}/ss:/etc/shadowsocks-rust"
