---
- name: Spawn ShadowSocks
  community.docker.docker_container:
    name: shadowsocks
    image: ghcr.io/shadowsocks/ssserver-rust:latest
    ports:
      - '4242:4242/tcp'
    restart_policy: unless-stopped
    volumes:
      - "{{ container_path }}/ss:/etc/shadowsocks-rust"
